name: task_6
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dartz: ^0.10.1
  # Service locator
  get_it: ^7.6.1
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Remote API
  connectivity_plus: ^4.0.2
  http: ^1.0.0

  rxdart: ^0.28.0
  # Local cache
  shared_preferences: ^2.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  build_runner: ^2.4.7
  mockito: ^5.4.3
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/
